export const gitList=[{value: 'Actionscript', label: 'Actionscript'},{value: 'Android', label: 'Android'},
    {value: 'AppceleratorTitanium', label: 'AppceleratorTitanium'},{value: 'Autotools', label: 'Autotools'},
    {value: 'C', label: 'C'},{value: 'C++', label: 'C++'},
    {value: 'CFWheels', label: 'CFWheels'},{value: 'CMake', label: 'CMake'},
    {value: 'CakePHP', label: 'CakePHP'},{value: 'Clojure', label: 'Clojure'},
    {value: 'CodeIgniter', label: 'CodeIgniter'}, {value: 'Concrete5', label: 'Concrete5'},
    {value: 'Coq', label: 'Coq'},{value: 'D', label: 'D'},
    {value: 'DM', label: 'DM'},{value: 'Dart', label: 'Dart'},
    {value: 'Delphi', label: 'Delphi'},{value: 'Django', label: 'Django'},
    {value: 'Drupal', label: 'Drupal'},{value: 'Eagle', label: 'Eagle'},
    {value: 'Elm', label: 'Elm'},{value: 'Erlang', label: 'Erlang'},
    {value: 'ExpressionEngine', label: 'ExpressionEngine'},{value: 'Finale', label: 'Finale'},
    {value: 'ForceDotCom', label: 'ForceDotCom'},{value: 'FuelPHP', label: 'FuelPHP'},
    {value: 'GWT', label: 'GWT'},{value: 'Gcov', label: 'Gcov'},
    {value: 'Go', label: 'Go'},{value: 'Godot', label: 'Godot'},
    {value: 'Grails', label: 'Grails'},{value: 'Haskell', label: 'Haskell'},
    {value: 'JENKINS_HOME', label: 'JENKINS_HOME'},{value: 'Java', label: 'Java'},
    {value: 'Jboss', label: 'Jboss'},{value: 'Jekyll', label: 'Jekyll'},
    {value: 'Joomla', label: 'Joomla'},{value: 'Julia', label: 'Julia'},
    {value: 'Jython', label: 'Jython'},{value: 'Kohana', label: 'Kohana'},
    {value: 'Kotlin', label: 'Kotlin'},{value: 'Leiningen', label: 'Leiningen'},
    {value: 'LemonStand', label: 'LemonStand'},{value: 'Lilypond', label: 'Lilypond'},
    {value: 'Lithium', label: 'Lithium'},{value: 'Magento', label: 'Magento'},
    {value: 'Maven', label: 'Maven'},{value: 'Nanoc', label: 'Nanoc'},
    {value: 'Node', label: 'Node'},{value: 'OCaml', label: 'OCaml'},
    {value: 'Objective-C', label: 'Objective-C'},{value: 'Opa', label: 'Opa'},
    {value: 'OpenCart', label: 'OpenCart'},{value: 'OracleForms', label: 'OracleForms'},
    {value: 'Perl', label: 'Perl'},{value: 'PlayFramework', label: 'PlayFramework'},
    {value: 'Plone', label: 'Plone'},{value: 'PureScript', label: 'PureScript'},
    {value: 'Python', label: 'Python'},{value: 'Qooxdoo', label: 'Qooxdoo'},
    {value: 'Qt', label: 'Qt'},{value: 'R', label: 'R'},
    {value: 'Rails', label: 'Rails'},{value: 'Raku', label: 'Raku'},
    {value: 'RhodesRhomobile', label: 'RhodesRhomobile'},
    {value: 'Ruby', label: 'Ruby'},{value: 'Rust', label: 'Rust'},
    {value: 'Scala', label: 'Scala'},{value: 'Scheme', label: 'Scheme'},
    {value: 'Sdcc', label: 'Sdcc'},{value: 'SeamGen', label: 'SeamGen'},
    {value: 'SketchUp', label: 'SketchUp'},{value: 'Smalltalk', label: 'Smalltalk'},
    {value: 'SugarCRM', label: 'SugarCRM'},{value: 'Swift', label: 'Swift'},
    {value: 'SymphonyCMS', label: 'SymphonyCMS'},{value: 'Terraform', label: 'Terraform'},
    {value: 'Textpattern', label: 'Textpattern'},{value: 'TurboGears2', label: 'TurboGears2'},
    {value: 'Typo3', label: 'Typo3'},{value: 'Unity', label: 'Unity'},
    {value: 'UnrealEngine', label: 'UnrealEngine'},{value: 'VisualStudio', label: 'VisualStudio'},
    {value: 'Waf', label: 'Waf'},{value: 'WordPress', label: 'WordPress'},
    {value: 'Yii', label: 'Yii'},{value: 'ZendFramework', label: 'ZendFramework'}

]

